import { useState } from 'react';
import { ChevronRight, BarChart2, ChevronLeft, RefreshCw, Download, FileText } from 'lucide-react';
import { generatePDF, inr, fmtD } from '../../utils/pdfReport';
import api from '../../services/api';
import { useAuth } from '../../context/AuthContext';

// ── Constants ─────────────────────────────────────────────────────────────────
const FEE_CATEGORIES = ['All','admission','Admission Fee','Application fee','CF FEE','Kit','Makeup','misc','Summer Exam Fee','Test Miscellaneous','TF FEE'];
const FEE_MODES      = ['All','offline','online'];
const MONTHS         = ['All','January','February','March','April','May','June','July','August','September','October','November','December'];
const YEARS          = ['All','2024','2025','2026'];

// ── Report sections ───────────────────────────────────────────────────────────
const REPORT_SECTIONS = [
  {
    title: 'Custom Reports',
    reports: [
      { key: 'daily_bank',       name: 'General Daily Bank Report' },
      { key: 'daily_collection', name: 'General Daily Collection Report' },
      { key: 'monthly_abstract', name: 'General Monthly Abstract Report' },
      { key: 'yearly_abstract',  name: 'General Yearly Abstract Report' },
    ],
  },
  {
    title: 'Pay Record',
    reports: [
      { key: 'pay_record_dcr', name: 'Pay Record DCR' },
    ],
  },
  {
    title: 'Fee Collection Report',
    reports: [
      { key: 'cancellation', name: 'Cancellation Report' },
      { key: 'daily_bank2',  name: 'Daily Bank Report' },
      { key: 'daily_coll2',  name: 'Daily Collection Report' },
      { key: 'refund',       name: 'Refund Report' },
    ],
  },
  {
    title: 'Financial & Abstract Report',
    reports: [
      { key: 'monthly_abs2', name: 'Monthly Abstract Report' },
      { key: 'yearly_abs2',  name: 'Yearly Abstract Report' },
    ],
  },
];

// ── Per-report config ─────────────────────────────────────────────────────────
const REPORT_CONFIGS = {
  daily_bank: {
    name: 'General Daily Bank Report',
    description: 'Daily bank-wise collection summary.',
    filters: [
      { id:'start_date', label:'Start Date', type:'date' },
      { id:'to_date',    label:'To Date',    type:'date' },
      { id:'fee_mode',   label:'Fee Mode',   type:'select', options: FEE_MODES },
    ],
    columns:['Report Name','Report Type','Fee Mode','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','fee_mode','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Customer Name','Amount (₹)','Method','Module','Date','Status'],
    apiPath: '/api/billing/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.customer_name||'—', inr(r.pay_amount), r.method||'—',
      r.module_name||'—', fmtD(r.captured_date), r.pay_status||'—',
    ]),
  },
  daily_collection: {
    name: 'General Daily Collection Report',
    description: 'Daily collection report for all billing transactions.',
    filters: [
      { id:'start_date',   label:'Start Date',  type:'date' },
      { id:'to_date',      label:'To Date',      type:'date' },
      { id:'fee_category', label:'Fee Category', type:'select', options: FEE_CATEGORIES },
    ],
    columns:['Report Name','Report Type','Fee Category','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','fee_category','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Customer Name','Amount (₹)','Method','Module','Date','Status'],
    apiPath: '/api/billing/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.customer_name||'—', inr(r.pay_amount), r.method||'—',
      r.module_name||'—', fmtD(r.captured_date), r.pay_status||'—',
    ]),
  },
  monthly_abstract: {
    name: 'General Monthly Abstract Report',
    description: 'Monthly abstract of all billing transactions.',
    filters: [
      { id:'month', label:'Month', type:'select', options: MONTHS },
      { id:'year',  label:'Year',  type:'select', options: YEARS },
    ],
    columns:['Report Name','Report Type','Month','Year','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','month','year','requested_at','generated_by','status'],
    pdfColumns: ['#','Customer Name','Amount (₹)','Method','Module','Date','Status'],
    apiPath: '/api/billing/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.customer_name||'—', inr(r.pay_amount), r.method||'—',
      r.module_name||'—', fmtD(r.captured_date), r.pay_status||'—',
    ]),
  },
  yearly_abstract: {
    name: 'General Yearly Abstract Report',
    description: 'Yearly abstract of all billing transactions.',
    filters: [
      { id:'year', label:'Year', type:'select', options: YEARS },
    ],
    columns:['Report Name','Report Type','Year','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','year','requested_at','generated_by','status'],
    pdfColumns: ['#','Customer Name','Amount (₹)','Method','Module','Date','Status'],
    apiPath: '/api/billing/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.customer_name||'—', inr(r.pay_amount), r.method||'—',
      r.module_name||'—', fmtD(r.captured_date), r.pay_status||'—',
    ]),
  },
  pay_record_dcr: {
    name: 'Pay Record DCR',
    description: 'Daily collection report from pay records.',
    filters: [
      { id:'fee_mode',     label:'Fee Mode',     type:'select', options: FEE_MODES },
      { id:'fee_category', label:'Fee Category', type:'select', options: FEE_CATEGORIES },
      { id:'start_date',   label:'Start Date',   type:'date' },
      { id:'to_date',      label:'To Date',       type:'date' },
    ],
    columns:['Report Name','Report Type','Fee Mode','Fee Category','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','fee_mode','fee_category','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Name','Ref No','Date','Amount (₹)','Method','Status'],
    apiPath: '/api/billing/pay-records',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.name||'—', r.ref_no||'—', fmtD(r.transaction_date),
      inr(r.transaction_amount), r.method||'—', r.status||'—',
    ]),
  },
  cancellation: {
    name: 'Cancellation Report',
    description: 'Report of all cancelled billing orders.',
    filters: [
      { id:'fee_category', label:'Fee Category', type:'select', options: FEE_CATEGORIES },
      { id:'start_date',   label:'Start Date',   type:'date' },
      { id:'to_date',      label:'To Date',       type:'date' },
    ],
    columns:['Report Name','Report Type','Fee Category','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','fee_category','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Customer Name','Customer ID','Fee Category','Amount (₹)','Order Status'],
    apiPath: '/api/billing/orders',
    pdfMapper: (records) => records
      .filter(r => r.order_status === 'cancelled' || r.order_status === 'refunded')
      .map((r, i) => [
        i+1, r.customer_name||'—', r.customer_id||'—', r.fee_category||'—',
        inr(r.fee_order_amount), r.order_status||'—',
      ]),
  },
  daily_bank2: {
    name: 'Daily Bank Report',
    filters: [
      { id:'start_date', label:'Start Date', type:'date' },
      { id:'to_date',    label:'To Date',    type:'date' },
    ],
    columns:['Report Name','Report Type','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Customer Name','Amount (₹)','Method','Module','Date','Status'],
    apiPath: '/api/billing/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.customer_name||'—', inr(r.pay_amount), r.method||'—',
      r.module_name||'—', fmtD(r.captured_date), r.pay_status||'—',
    ]),
  },
  daily_coll2: {
    name: 'Daily Collection Report',
    filters: [
      { id:'start_date', label:'Start Date', type:'date' },
      { id:'to_date',    label:'To Date',    type:'date' },
    ],
    columns:['Report Name','Report Type','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Customer Name','Amount (₹)','Method','Module','Date','Status'],
    apiPath: '/api/billing/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.customer_name||'—', inr(r.pay_amount), r.method||'—',
      r.module_name||'—', fmtD(r.captured_date), r.pay_status||'—',
    ]),
  },
  refund: {
    name: 'Refund Report',
    filters: [
      { id:'start_date',   label:'Start Date',  type:'date' },
      { id:'to_date',      label:'To Date',      type:'date' },
      { id:'fee_category', label:'Fee Category', type:'select', options: FEE_CATEGORIES },
    ],
    columns:['Report Name','Report Type','Fee Category','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','fee_category','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Customer Name','Customer ID','Fee Category','Amount (₹)','Order Status'],
    apiPath: '/api/billing/orders',
    pdfMapper: (records) => records
      .filter(r => r.order_status === 'refunded')
      .map((r, i) => [
        i+1, r.customer_name||'—', r.customer_id||'—', r.fee_category||'—',
        inr(r.fee_order_amount), r.order_status||'—',
      ]),
  },
  monthly_abs2: {
    name: 'Monthly Abstract Report',
    filters: [
      { id:'month', label:'Month', type:'select', options: MONTHS },
      { id:'year',  label:'Year',  type:'select', options: YEARS },
    ],
    columns:['Report Name','Report Type','Month','Year','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','month','year','requested_at','generated_by','status'],
    pdfColumns: ['#','Customer Name','Amount (₹)','Method','Module','Date','Status'],
    apiPath: '/api/billing/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.customer_name||'—', inr(r.pay_amount), r.method||'—',
      r.module_name||'—', fmtD(r.captured_date), r.pay_status||'—',
    ]),
  },
  yearly_abs2: {
    name: 'Yearly Abstract Report',
    filters: [
      { id:'year', label:'Year', type:'select', options: YEARS },
    ],
    columns:['Report Name','Report Type','Year','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','year','requested_at','generated_by','status'],
    pdfColumns: ['#','Customer Name','Amount (₹)','Method','Module','Date','Status'],
    apiPath: '/api/billing/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.customer_name||'—', inr(r.pay_amount), r.method||'—',
      r.module_name||'—', fmtD(r.captured_date), r.pay_status||'—',
    ]),
  },
};

function SelectFilter({ label, options, value, onChange }) {
  return (
    <div className="flex flex-col gap-0.5 min-w-[160px]">
      <label className="text-[10px] text-slate-500 uppercase tracking-wide px-0.5">{label}</label>
      <select value={value} onChange={(e) => onChange(e.target.value)}
        className="px-3 py-2 text-sm bg-white border border-slate-300 rounded-lg text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-400">
        {options.map((o) => <option key={o} value={o}>{o}</option>)}
      </select>
    </div>
  );
}

function DateFilter({ label, value, onChange }) {
  return (
    <div className="flex flex-col gap-0.5 min-w-[160px]">
      <label className="text-[10px] text-slate-500 uppercase tracking-wide px-0.5">{label}</label>
      <input type="date" value={value} onChange={(e) => onChange(e.target.value)}
        className="px-3 py-2 text-sm bg-white border border-slate-300 rounded-lg text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-400" />
    </div>
  );
}

function fmtDate(iso) {
  if (!iso) return '—';
  const d = new Date(iso);
  return `${String(d.getDate()).padStart(2,'0')} ${d.toLocaleString('en',{month:'short'})} ${d.getFullYear()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')} ${d.getHours()>=12?'PM':'AM'}`;
}

function ReportDetailPage({ reportKey, onBack }) {
  const cfg = REPORT_CONFIGS[reportKey];
  const { tenant } = useAuth();
  const initF = () => {
    const f = {};
    cfg.filters.forEach((fi) => { f[fi.id] = fi.type === 'date' ? '' : (fi.options?.[0] || ''); });
    return f;
  };
  const [filters, setFilters] = useState(initF);
  const [rows, setRows] = useState(() => {
    try { return JSON.parse(localStorage.getItem(`bill_report_${reportKey}`) || '[]'); }
    catch { return []; }
  });
  const [generating, setGenerating] = useState(false);
  const [downloadingId, setDownloadingId] = useState(null);
  const [error, setError] = useState(null);

  const saveRows = (r) => { setRows(r); localStorage.setItem(`bill_report_${reportKey}`, JSON.stringify(r)); };

  const buildFilterSummary = (f) => {
    const summary = {};
    cfg.filters.forEach((fi) => {
      const v = f[fi.id];
      if (v && v !== '' && v !== 'All') summary[fi.label] = v;
    });
    return summary;
  };

  const fetchAndBuildPdf = async (filterSummary) => {
    const { data: resp } = await api.get(cfg.apiPath, { params: { limit: 500 } });
    const records = resp.data || resp || [];
    const pdfRows = cfg.pdfMapper(records);
    generatePDF({
      title: cfg.name,
      filters: filterSummary,
      columns: cfg.pdfColumns,
      rows: pdfRows,
      filename: `${cfg.name.replace(/\s+/g, '_')}_${Date.now()}`,
      institution: tenant?.name,
    });
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);
    try {
      const filterSummary = buildFilterSummary(filters);
      await fetchAndBuildPdf(filterSummary);

      const newRow = {
        id: Date.now(),
        name: cfg.name,
        report_type: 'PDF',
        fee_mode:     filters.fee_mode || 'All',
        fee_category: filters.fee_category || 'All',
        month:        filters.month || 'All',
        year:         filters.year || 'All',
        start_date:   filters.start_date || '—',
        to_date:      filters.to_date || '—',
        requested_at: fmtDate(new Date().toISOString()),
        generated_by: 'Admin',
        status:       'Download',
        _filterSummary: filterSummary,
      };
      saveRows([newRow, ...rows]);
    } catch (err) {
      console.error(err);
      setError('Failed to generate report. Please check your connection and try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = async (row) => {
    setDownloadingId(row.id);
    try {
      await fetchAndBuildPdf(row._filterSummary || {});
    } catch (err) {
      console.error(err);
      setError('Failed to download report. Please try again.');
    } finally {
      setDownloadingId(null);
    }
  };

  const getValue = (row, key) => row[key] ?? '—';

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <button onClick={onBack} className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-500 transition-colors">
            <ChevronLeft size={18} />
          </button>
          <div>
            <h1 className="text-lg font-bold text-slate-800">{cfg.name}</h1>
            {cfg.description && <p className="text-xs text-slate-500">{cfg.description}</p>}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => setFilters(initF())} className="p-2 rounded-lg hover:bg-slate-100 text-slate-500" title="Reset"><RefreshCw size={15} /></button>
          <button onClick={handleGenerate} disabled={generating}
            className="flex items-center gap-2 px-4 py-2 text-sm font-semibold bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-60">
            {generating ? 'Generating…' : 'Generate'}
          </button>
        </div>
      </div>

      {error && (
        <div className="px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">{error}</div>
      )}

      <div className="bg-white rounded-xl border border-slate-200 p-4">
        <div className="flex flex-wrap gap-3">
          {cfg.filters.map((fi) => fi.type === 'date' ? (
            <DateFilter key={fi.id} label={fi.label} value={filters[fi.id]||''} onChange={(v) => setFilters((f) => ({...f,[fi.id]:v}))} />
          ) : (
            <SelectFilter key={fi.id} label={fi.label} options={fi.options} value={filters[fi.id]||fi.options[0]} onChange={(v) => setFilters((f) => ({...f,[fi.id]:v}))} />
          ))}
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        {rows.length === 0 ? (
          <div className="py-20 text-center">
            <FileText size={36} className="mx-auto mb-3 text-slate-300" />
            <p className="text-sm font-medium text-slate-500">
              To Generate the report, please select all filters above and click on the &apos;Generate&apos; button to download the report.
            </p>
            <p className="text-xs text-slate-400 mt-1">You can select the type of report you want to generate and download it in either Excel or PDF format.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-100">
                  {cfg.columns.map((col) => (
                    <th key={col} className="px-4 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wide whitespace-nowrap">{col}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {rows.map((row) => (
                  <tr key={row.id} className="hover:bg-slate-50">
                    {cfg.rowKeys.map((key, i) => (
                      <td key={i} className="px-4 py-3 text-slate-600 text-xs whitespace-nowrap">
                        {key === 'status' ? (
                          <button
                            onClick={() => handleDownload(row)}
                            disabled={downloadingId === row.id}
                            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-60 transition-colors">
                            <Download size={11} /> {downloadingId === row.id ? 'Downloading…' : 'Download'}
                          </button>
                        ) : key === 'name' ? (
                          <span className="font-medium text-slate-800">{getValue(row,key)}</span>
                        ) : key === 'report_type' ? (
                          <span className="px-2 py-0.5 bg-orange-100 text-orange-700 rounded text-xs font-medium">{getValue(row,key)}</span>
                        ) : getValue(row,key)}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

export default function BillingReportsPage() {
  const [selected, setSelected] = useState(null);

  if (selected) return <ReportDetailPage reportKey={selected} onBack={() => setSelected(null)} />;

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-blue-600 flex items-center justify-center">
          <BarChart2 size={20} className="text-white" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-slate-800">Billing Reports</h1>
          <p className="text-sm text-slate-500 mt-0.5">Generate billing and financial reports</p>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {REPORT_SECTIONS.map((section) => (
          <div key={section.title} className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="px-5 py-4 border-b border-slate-100">
              <h3 className="font-semibold text-slate-800 text-sm">{section.title}</h3>
            </div>
            <div className="p-2">
              {section.reports.map((r) => (
                <button key={r.key} onClick={() => setSelected(r.key)}
                  className="w-full flex items-center justify-between px-4 py-3 text-sm text-slate-700 hover:bg-slate-50 transition-colors rounded-lg group">
                  <span className="group-hover:text-blue-600 transition-colors text-left">{r.name}</span>
                  <ChevronRight size={14} className="text-slate-400 group-hover:text-blue-500 flex-shrink-0" />
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
