import { useState } from 'react';
import { ChevronRight, BarChart2, ChevronLeft, RefreshCw, Download, FileText } from 'lucide-react';
import { generatePDF, inr, fmtD } from '../../utils/pdfReport';
import api from '../../services/api';
import { useAuth } from '../../context/AuthContext';

// ── Constants ─────────────────────────────────────────────────────────────────
const PROGRAMS = ['All','Computer Science and Engineering','Electronics and Communication Engineering','Mechanical Engineering','Civil Engineering','Electrical and Electronics Engineering'];
const STREAMS  = ['All','BE','MBA','MCA','ME'];
const STATUSES_SCH = ['All','Applied','Sanctioned','Rejected','Pending'];
const YEARS    = ['All','1','2','3','4'];
const SORT_BY  = ['Student Name','USN'];

// ── Report sections ───────────────────────────────────────────────────────────
const REPORT_SECTIONS = [
  {
    title: 'Student Reports',
    reports: [
      { key: 'active_students',   name: 'Active Students Report' },
      { key: 'inactive_students', name: 'Inactive Students Report' },
      { key: 'student_summary',   name: 'Student Summary Report' },
    ],
  },
  {
    title: 'Scholarship Reports',
    reports: [
      { key: 'applied_scholarship',    name: 'Applied Scholarships Report' },
      { key: 'sanctioned_scholarship', name: 'Sanctioned Scholarships Report' },
      { key: 'scholarship_summary',    name: 'Scholarship Summary' },
    ],
  },
  {
    title: 'Bank Loan Reports',
    reports: [
      { key: 'active_loans', name: 'Active Loans Report' },
      { key: 'loan_summary', name: 'Loan Summary Report' },
    ],
  },
];

// ── Report configs ────────────────────────────────────────────────────────────
const REPORT_CONFIGS = {
  active_students: {
    name: 'Active Students Report',
    description: 'List of all currently active students.',
    filters: [
      { id:'stream',   label:'Stream',  type:'select', options: STREAMS },
      { id:'program',  label:'Program', type:'select', options: PROGRAMS },
      { id:'year',     label:'Year',    type:'select', options: YEARS },
      { id:'sort_by',  label:'Sort by', type:'select', options: SORT_BY },
    ],
    columns:['Report Name','Report Type','Stream','Program','Year','Sort By','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','stream','program','year','sort_by','requested_at','generated_by','status'],
    pdfColumns: ['#','Name','Mobile','Email','Stream','Program','Status'],
    apiPath: '/api/general/students',
    apiParams: { status: 'Active' },
    pdfMapper: (records) => records
      .filter(r => r.status === 'Active' || !r.status)
      .map((r, i) => [i+1, r.name||'—', r.mobile_number||'—', r.email||'—', r.stream||'—', r.program||'—', r.status||'Active']),
  },
  inactive_students: {
    name: 'Inactive Students Report',
    description: 'List of all inactive / ex-students.',
    filters: [
      { id:'stream',   label:'Stream',  type:'select', options: STREAMS },
      { id:'program',  label:'Program', type:'select', options: PROGRAMS },
      { id:'sort_by',  label:'Sort by', type:'select', options: SORT_BY },
    ],
    columns:['Report Name','Report Type','Stream','Program','Sort By','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','stream','program','sort_by','requested_at','generated_by','status'],
    pdfColumns: ['#','Name','Mobile','Email','Stream','Program','Status'],
    apiPath: '/api/general/students',
    apiParams: { status: 'Inactive' },
    pdfMapper: (records) => records
      .filter(r => r.status === 'Inactive')
      .map((r, i) => [i+1, r.name||'—', r.mobile_number||'—', r.email||'—', r.stream||'—', r.program||'—', r.status||'Inactive']),
  },
  student_summary: {
    name: 'Student Summary Report',
    description: 'Summary count of students grouped by stream and program.',
    filters: [
      { id:'stream',  label:'Stream',  type:'select', options: STREAMS },
      { id:'program', label:'Program', type:'select', options: PROGRAMS },
    ],
    columns:['Report Name','Report Type','Stream','Program','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','stream','program','requested_at','generated_by','status'],
    pdfColumns: ['#','Name','Mobile','Email','Stream','Program','Status'],
    apiPath: '/api/general/students',
    apiParams: {},
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.name||'—', r.mobile_number||'—', r.email||'—', r.stream||'—', r.program||'—', r.status||'—',
    ]),
  },
  applied_scholarship: {
    name: 'Applied Scholarships Report',
    description: 'All scholarship applications that have been submitted.',
    filters: [
      { id:'academic_year', label:'Academic Year', type:'select', options:['All','2024-2025','2025-2026','2026-2027'] },
      { id:'status',        label:'Status',        type:'select', options: STATUSES_SCH },
    ],
    columns:['Report Name','Report Type','Academic Year','Status','Requested At','Generated By','Status Col'],
    rowKeys: ['name','report_type','academic_year','status_val','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','Application No','Academic Year','Amount (₹)','Status','Term'],
    apiPath: '/api/general/scholarships',
    apiParams: {},
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.application_no||'—', r.academic_year||'—',
      inr(r.scholarship_amount), r.scholarship_status||'—', r.term||'—',
    ]),
  },
  sanctioned_scholarship: {
    name: 'Sanctioned Scholarships Report',
    description: 'All scholarships that have been approved and sanctioned.',
    filters: [
      { id:'academic_year', label:'Academic Year', type:'select', options:['All','2024-2025','2025-2026','2026-2027'] },
    ],
    columns:['Report Name','Report Type','Academic Year','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','academic_year','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','Application No','Academic Year','Amount (₹)','Status','Term'],
    apiPath: '/api/general/scholarships',
    apiParams: { status: 'approved' },
    pdfMapper: (records) => records
      .filter(r => r.scholarship_status === 'approved')
      .map((r, i) => [
        i+1, r.student_name||'—', r.application_no||'—', r.academic_year||'—',
        inr(r.scholarship_amount), r.scholarship_status||'—', r.term||'—',
      ]),
  },
  scholarship_summary: {
    name: 'Scholarship Summary',
    description: 'Overview summary of all scholarships by status.',
    filters: [
      { id:'academic_year', label:'Academic Year', type:'select', options:['All','2024-2025','2025-2026','2026-2027'] },
      { id:'status',        label:'Status',        type:'select', options: STATUSES_SCH },
    ],
    columns:['Report Name','Report Type','Academic Year','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','academic_year','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','Application No','Academic Year','Amount (₹)','Status','Term'],
    apiPath: '/api/general/scholarships',
    apiParams: {},
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.application_no||'—', r.academic_year||'—',
      inr(r.scholarship_amount), r.scholarship_status||'—', r.term||'—',
    ]),
  },
  active_loans: {
    name: 'Active Loans Report',
    description: 'All currently active bank loans.',
    filters: [
      { id:'loan_type', label:'Loan Type', type:'select', options:['All','Student Loan','Education Loan','Personal Loan','Other'] },
      { id:'bank_name', label:'Bank',      type:'select', options:['All','SBI','HDFC','ICICI','PNB','Canara Bank'] },
    ],
    columns:['Report Name','Report Type','Loan Type','Bank','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','loan_type','bank_name','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','Bank','Ref No','Loan Type','Amount (₹)','Loan Date','Status'],
    apiPath: '/api/general/bank-loans',
    apiParams: { status: 'active' },
    pdfMapper: (records) => records
      .filter(r => r.status === 'active')
      .map((r, i) => [
        i+1, r.student_name||'—', r.bank_name||'—', r.reference_number||'—',
        r.loan_type||'—', inr(r.amount), fmtD(r.loan_date), r.status||'—',
      ]),
  },
  loan_summary: {
    name: 'Loan Summary Report',
    description: 'Summary of all loan records grouped by bank and type.',
    filters: [
      { id:'loan_type', label:'Loan Type', type:'select', options:['All','Student Loan','Education Loan','Personal Loan','Other'] },
    ],
    columns:['Report Name','Report Type','Loan Type','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','loan_type','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','Bank','Ref No','Account No','Loan Type','Amount (₹)','Loan Date','Status'],
    apiPath: '/api/general/bank-loans',
    apiParams: {},
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.bank_name||'—', r.reference_number||'—',
      r.account_number||'—', r.loan_type||'—', inr(r.amount), fmtD(r.loan_date), r.status||'—',
    ]),
  },
};

function SelectFilter({ label, options, value, onChange }) {
  return (
    <div className="flex flex-col gap-0.5 min-w-[160px]">
      <label className="text-[10px] text-slate-500 uppercase tracking-wide px-0.5">{label}</label>
      <select value={value} onChange={(e) => onChange(e.target.value)}
        className="px-3 py-2 text-sm bg-white border border-slate-300 rounded-lg text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-400">
        {options.map((o) => <option key={o} value={o}>{o}</option>)}
      </select>
    </div>
  );
}

function fmtDate(iso) {
  if (!iso) return '—';
  const d = new Date(iso);
  return `${String(d.getDate()).padStart(2,'0')} ${d.toLocaleString('en',{month:'short'})} ${d.getFullYear()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')} ${d.getHours()>=12?'PM':'AM'}`;
}

function ReportDetailPage({ reportKey, onBack }) {
  const cfg = REPORT_CONFIGS[reportKey];
  const { tenant } = useAuth();
  const initFilters = () => {
    const f = {};
    cfg.filters.forEach((fi) => { f[fi.id] = fi.options[0]; });
    return f;
  };
  const [filters, setFilters] = useState(initFilters);
  const [rows, setRows] = useState(() => {
    try { return JSON.parse(localStorage.getItem(`gen_report_${reportKey}`) || '[]'); }
    catch { return []; }
  });
  const [generating, setGenerating] = useState(false);
  const [downloadingId, setDownloadingId] = useState(null);
  const [error, setError] = useState(null);

  const saveRows = (r) => { setRows(r); localStorage.setItem(`gen_report_${reportKey}`, JSON.stringify(r)); };

  const buildFilterSummary = (f) => {
    const summary = {};
    cfg.filters.forEach((fi) => {
      const v = f[fi.id];
      if (v && v !== 'All') summary[fi.label] = v;
    });
    return summary;
  };

  const fetchAndBuildPdf = async (filterSummary) => {
    const { data: resp } = await api.get(cfg.apiPath, { params: { ...cfg.apiParams, limit: 500 } });
    const records = resp.data || resp || [];
    const pdfRows = cfg.pdfMapper(records);
    generatePDF({
      title: cfg.name,
      filters: filterSummary,
      columns: cfg.pdfColumns,
      rows: pdfRows,
      filename: `${cfg.name.replace(/\s+/g, '_')}_${Date.now()}`,
      institution: tenant?.name,
    });
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);
    try {
      const filterSummary = buildFilterSummary(filters);
      await fetchAndBuildPdf(filterSummary);

      const newRow = {
        id: Date.now(),
        name: cfg.name,
        report_type: 'PDF',
        stream:        filters.stream || 'All',
        program:       filters.program || 'All',
        year:          filters.year || 'All',
        sort_by:       filters.sort_by || 'Student Name',
        academic_year: filters.academic_year || 'All',
        status_val:    filters.status || 'All',
        loan_type:     filters.loan_type || 'All',
        bank_name:     filters.bank_name || 'All',
        requested_at:  fmtDate(new Date().toISOString()),
        generated_by:  'Admin',
        status:        'Download',
        _filterSummary: filterSummary,
      };
      saveRows([newRow, ...rows]);
    } catch (err) {
      console.error(err);
      setError('Failed to generate report. Please check your connection and try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = async (row) => {
    setDownloadingId(row.id);
    try {
      await fetchAndBuildPdf(row._filterSummary || {});
    } catch (err) {
      console.error(err);
      setError('Failed to download report. Please try again.');
    } finally {
      setDownloadingId(null);
    }
  };

  const getValue = (row, key) => ({
    name:'',report_type:'',stream:'',program:'',year:'',sort_by:'',
    academic_year:'',status_val:'',loan_type:'',bank_name:'',
    requested_at:'',generated_by:'',status:'', ...row,
  }[key] ?? '—');

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <button onClick={onBack} className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-500 transition-colors">
            <ChevronLeft size={18} />
          </button>
          <div>
            <h1 className="text-lg font-bold text-slate-800">{cfg.name}</h1>
            {cfg.description && <p className="text-xs text-slate-500">{cfg.description}</p>}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => setFilters(initFilters())} className="p-2 rounded-lg hover:bg-slate-100 text-slate-500" title="Reset">
            <RefreshCw size={15} />
          </button>
          <button onClick={handleGenerate} disabled={generating}
            className="flex items-center gap-2 px-4 py-2 text-sm font-semibold bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-60 transition-colors">
            {generating ? 'Generating…' : 'Generate'}
          </button>
        </div>
      </div>

      {error && (
        <div className="px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">{error}</div>
      )}

      <div className="bg-white rounded-xl border border-slate-200 p-4">
        <div className="flex flex-wrap gap-3">
          {cfg.filters.map((fi) => (
            <SelectFilter key={fi.id} label={fi.label} options={fi.options}
              value={filters[fi.id] || fi.options[0]}
              onChange={(v) => setFilters((f) => ({ ...f, [fi.id]: v }))} />
          ))}
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        {rows.length === 0 ? (
          <div className="py-20 text-center">
            <FileText size={36} className="mx-auto mb-3 text-slate-300" />
            <p className="text-sm font-medium text-slate-500">To Generate the report, please select all filters above and click on the &apos;Generate&apos; button to download the report.</p>
            <p className="text-xs text-slate-400 mt-1">You can select the type of report you want to generate and download it in either Excel or PDF format.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-100">
                  {cfg.columns.map((col) => (
                    <th key={col} className="px-4 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wide whitespace-nowrap">{col}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {rows.map((row) => (
                  <tr key={row.id} className="hover:bg-slate-50 transition-colors">
                    {cfg.rowKeys.map((key, i) => (
                      <td key={i} className="px-4 py-3 text-slate-600 text-xs whitespace-nowrap">
                        {key === 'status' ? (
                          <button
                            onClick={() => handleDownload(row)}
                            disabled={downloadingId === row.id}
                            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-60 transition-colors">
                            <Download size={11} /> {downloadingId === row.id ? 'Downloading…' : 'Download'}
                          </button>
                        ) : key === 'name' ? (
                          <span className="font-medium text-slate-800">{getValue(row, key)}</span>
                        ) : key === 'report_type' ? (
                          <span className="px-2 py-0.5 bg-orange-100 text-orange-700 rounded text-xs font-medium">{getValue(row, key)}</span>
                        ) : getValue(row, key)}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

export default function GeneralReportsPage() {
  const [selected, setSelected] = useState(null);

  if (selected) return <ReportDetailPage reportKey={selected} onBack={() => setSelected(null)} />;

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-blue-600 flex items-center justify-center">
          <BarChart2 size={20} className="text-white" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-slate-800">General Reports</h1>
          <p className="text-sm text-slate-500 mt-0.5">Generate reports for general data</p>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {REPORT_SECTIONS.map((section) => (
          <div key={section.title} className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="px-5 py-4 border-b border-slate-100">
              <h3 className="font-semibold text-slate-800 text-sm">{section.title}</h3>
            </div>
            <div className="p-2">
              {section.reports.map((r) => (
                <button key={r.key} onClick={() => setSelected(r.key)}
                  className="w-full flex items-center justify-between px-4 py-3 text-sm text-slate-700 hover:bg-slate-50 transition-colors rounded-lg group">
                  <span className="group-hover:text-blue-600 transition-colors text-left">{r.name}</span>
                  <ChevronRight size={14} className="text-slate-400 group-hover:text-blue-500 flex-shrink-0" />
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
