import { useState, useRef, useEffect } from 'react';
import { ChevronRight, BarChart2, ChevronLeft, RefreshCw, Download, FileText } from 'lucide-react';
import { generatePDF, inr, fmtD } from '../../utils/pdfReport';
import api from '../../services/api';

// ── Constants ─────────────────────────────────────────────────────────────────
const FEE_CATEGORIES = [
  'All','admission','Admission Fee','Application fee','CF FEE','Kit',
  'Makeup','misc','my category','nnn','Summer Exam Fee','Test Miscellaneous','TF FEE',
];
const PROGRAMS = [
  'All','Biotechnology Engineering','Mechanical Engineering','Chemical Engineering',
  'Computer Science and Engineering','Electrical and Electronics Engineering',
  'Computer Science and Engineering (Data Science)','First Year',
  'Computer Science and Business Systems','Electronics and Communication Engineering',
  'Artificial Intelligence and Machine Learning','Information Science and Engineering',
  'Electronics and Instrumentation Engineering','Textile Engineering',
  'Civil Engineering','Computer Science and Design',
];
const QUOTAS        = ['All', 'MNG', 'CET'];
const YEARS         = ['All', '1', '2', '3', '4', 'Output Students'];
const STUDENT_TYPES = ['Select', 'All', 'Regular', 'Lateral Entry'];
const SORT_BY_USN   = ['USN', 'Student Name'];
const SORT_BY_TXN   = ['USN', 'Student Name', 'Transaction Date'];
const CATEGORIES    = ['All', 'SC/ST'];
const REPORT_TYPES  = ['Select Report Type', 'All', 'Balance Only'];
const FEE_MODES     = ['All', 'offline', 'online'];
const MONTHS        = ['All','January','February','March','April','May','June','July','August','September','October','November','December'];
const YEARS_ABS     = ['All','2024','2025','2026'];

// ── Report sections ───────────────────────────────────────────────────────────
const REPORT_SECTIONS = [
  {
    title: 'Custom Reports',
    reports: [
      { key: 'payrecord_dcr', name: 'Pay Record DCR' },
      { key: 'cancellation',  name: 'Cancellation Report' },
    ],
  },
  {
    title: 'Demand Collection & Balance Report',
    reports: [
      { key: 'balance',             name: 'Balance Report' },
      { key: 'consol_balance',      name: 'Consolidated Balance Report' },
      { key: 'consol_demand_coll',  name: 'Consolidated Demand Collection Report' },
      { key: 'consol',              name: 'Consolidated Report' },
      { key: 'demand_coll',         name: 'Demand Collection Report' },
      { key: 'demand',              name: 'Demand Report' },
      { key: 'headwise_demand_coll',name: 'Head-wise Demand Collection Report' },
    ],
  },
  {
    title: 'Fee Collection Report',
    reports: [
      { key: 'daily_bank',       name: 'Daily Bank Report' },
      { key: 'daily_collection', name: 'Daily Collection Report' },
      { key: 'excess_fee',       name: 'Excess Fee Report' },
      { key: 'refund',           name: 'Refund Report' },
    ],
  },
  {
    title: 'Financial & Abstract Report',
    reports: [
      { key: 'monthly_abstract', name: 'Monthly Abstract Report' },
      { key: 'student_consol',   name: 'Student-wise Consolidated Balance' },
    ],
  },
];

// ── Per-report config ─────────────────────────────────────────────────────────
const REPORT_CONFIGS = {
  balance: {
    name: 'Balance Report',
    filters: [
      { id:'fee_category', label:'Select fee category', type:'multi', options: FEE_CATEGORIES },
      { id:'programs',     label:'Select Programs',     type:'multi', options: PROGRAMS },
      { id:'quota',        label:'Select Quota',        type:'select',options: QUOTAS },
      { id:'year',         label:'Year',                type:'select',options: YEARS },
      { id:'student_type', label:'Student Type',        type:'select',options: STUDENT_TYPES },
    ],
    columns:['Report Name','Report Type','Program','Quota','Year','Student Type','Fee Category','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','program','quota','year','student_type','fee_category','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Fee Category','Demand (₹)','Collected (₹)','Balance (₹)'],
    apiPath: '/api/fee/orders',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', r.fee_category||'—',
      inr(r.fee_order_amount), inr(r.fee_paid_amount),
      inr((r.fee_order_amount||0)-(r.fee_paid_amount||0)),
    ]),
  },
  consol_balance: {
    name: 'Consolidated Balance Report',
    filters: [
      { id:'fee_category', label:'Select fee category', type:'multi', options: FEE_CATEGORIES },
      { id:'programs',     label:'Select Programs',     type:'multi', options: PROGRAMS },
      { id:'quota',        label:'Select Quota',        type:'select',options: QUOTAS },
      { id:'year',         label:'Year',                type:'select',options: YEARS },
      { id:'student_type', label:'Student Type',        type:'select',options: STUDENT_TYPES },
      { id:'sort_by',      label:'Sort by',             type:'select',options: SORT_BY_USN },
      { id:'category',     label:'Category',            type:'select',options: CATEGORIES },
    ],
    columns:['Report Name','Report Type','Program','Quota','Year','Fee Category','Sort By','Category','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','program','quota','year','fee_category','sort_by','category','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Program','Quota','Fee Category','Demand (₹)','Collected (₹)','Balance (₹)'],
    apiPath: '/api/fee/orders',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', r.program||'—', r.quota||'—', r.fee_category||'—',
      inr(r.fee_order_amount), inr(r.fee_paid_amount),
      inr((r.fee_order_amount||0)-(r.fee_paid_amount||0)),
    ]),
  },
  consol_demand_coll: {
    name: 'Consolidated Demand Collection Report',
    filters: [
      { id:'fee_category',  label:'Select fee category', type:'multi', options: FEE_CATEGORIES },
      { id:'programs',      label:'Program Name',        type:'multi', options: PROGRAMS },
      { id:'quota',         label:'Select Quota',        type:'select',options: QUOTAS },
      { id:'year',          label:'Year',                type:'select',options: YEARS },
      { id:'student_type',  label:'Student Type',        type:'select',options:['Select','Regular Students','Output Students'] },
      { id:'report_type',   label:'Select Report Type',  type:'select',options: REPORT_TYPES },
      { id:'sort_by',       label:'Sort by',             type:'select',options: SORT_BY_USN },
    ],
    columns:['Report Name','Report Type','Program','Quota','Term','Fee Category','Student Type','Sort By','Completion Year','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','program','quota','term','fee_category','student_type','sort_by','year','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Program','Quota','Fee Category','Demand (₹)','Collected (₹)','Balance (₹)'],
    apiPath: '/api/fee/orders',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', r.program||'—', r.quota||'—', r.fee_category||'—',
      inr(r.fee_order_amount), inr(r.fee_paid_amount),
      inr((r.fee_order_amount||0)-(r.fee_paid_amount||0)),
    ]),
  },
  consol: {
    name: 'Consolidated Report',
    filters: [
      { id:'fee_category',  label:'Select fee category', type:'multi', options: FEE_CATEGORIES },
      { id:'programs',      label:'Program Name',        type:'multi', options: PROGRAMS },
      { id:'year',          label:'Year',                type:'select',options: YEARS },
      { id:'student_type',  label:'Student Type',        type:'select',options: STUDENT_TYPES },
      { id:'report_type',   label:'Select Report Type',  type:'select',options: REPORT_TYPES },
      { id:'sort_by',       label:'Sort by',             type:'select',options: SORT_BY_USN },
    ],
    columns:['Report Name','Report Type','Program','Term','Fee Category','Report Type','Sort By','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','program','term','fee_category','report_type_val','sort_by','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Fee Category','Amount (₹)','Status'],
    apiPath: '/api/fee/orders',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', r.fee_category||'—',
      inr(r.fee_order_amount), r.order_status||'—',
    ]),
  },
  demand_coll: {
    name: 'Demand Collection Report',
    description: 'A report summarizing the collection of payments or dues against the expected demand over a specific period.',
    filters: [
      { id:'fee_category',  label:'Select fee category', type:'multi', options: FEE_CATEGORIES },
      { id:'programs',      label:'Program Name',        type:'multi', options: PROGRAMS },
      { id:'quota',         label:'Select Quota',        type:'select',options: QUOTAS },
      { id:'year',          label:'Year',                type:'select',options: YEARS },
      { id:'student_type',  label:'Student Type',        type:'select',options: STUDENT_TYPES },
      { id:'sort_by',       label:'Sort by',             type:'select',options: SORT_BY_USN },
      { id:'category',      label:'Category',            type:'select',options: CATEGORIES },
    ],
    columns:['Report Name','Report Type','Program','Quota','Term','Fee Category','Student Type','Sort By','Seat Category','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','program','quota','term','fee_category','student_type','sort_by','category','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Quota','Fee Category','Demand (₹)','Collected (₹)','Balance (₹)'],
    apiPath: '/api/fee/orders',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', r.quota||'—', r.fee_category||'—',
      inr(r.fee_order_amount), inr(r.fee_paid_amount),
      inr((r.fee_order_amount||0)-(r.fee_paid_amount||0)),
    ]),
  },
  demand: {
    name: 'Demand Report',
    filters: [
      { id:'fee_category',  label:'Select fee category', type:'multi', options: FEE_CATEGORIES },
      { id:'programs',      label:'Program Name',        type:'multi', options: PROGRAMS },
      { id:'quota',         label:'Select Quota',        type:'select',options: QUOTAS },
      { id:'year',          label:'Year',                type:'select',options: YEARS },
      { id:'student_type',  label:'Student Type',        type:'select',options: STUDENT_TYPES },
    ],
    columns:['Report Name','Report Type','Program','Quota','Term','Fee Category','Student Type','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','program','quota','term','fee_category','student_type','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Fee Category','Year','Demand Amount (₹)'],
    apiPath: '/api/fee/orders',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', r.fee_category||'—',
      r.year_of_study||'—', inr(r.fee_order_amount),
    ]),
  },
  headwise_demand_coll: {
    name: 'Head-wise Demand Collection Report',
    filters: [
      { id:'fee_category',  label:'Fee Category',    type:'select', options:['Select','Admission','Admission Fee','Application Fee','Cf Fee','Kit','Makeup','Misc','My Category','Nnn','Summer Exam Fee','Test Miscellaneous','Tf Fee'] },
      { id:'fee_heads',     label:'Select fee heads',type:'select', options:['All','Tuition Fee','Exam Fee','Library Fee','Lab Fee','Hostel Fee'] },
      { id:'programs',      label:'Program Name',    type:'multi',  options: PROGRAMS },
      { id:'quota',         label:'Select Quota',    type:'select', options: QUOTAS },
      { id:'year',          label:'Year',            type:'select', options: YEARS },
      { id:'student_type',  label:'Student Type',    type:'select', options: STUDENT_TYPES },
      { id:'sort_by',       label:'Sort by',         type:'select', options: SORT_BY_TXN },
    ],
    columns:['Report Name','Report Type','Program','Quota','Term','Fee Category','Fee Heads','Student Type','Sort By','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','program','quota','term','fee_category','fee_heads','student_type','sort_by','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Fee Category','Fee Head','Demand (₹)','Collected (₹)','Balance (₹)'],
    apiPath: '/api/fee/orders',
    pdfMapper: (records) => records.flatMap((r, i) =>
      (r.fee_particulars||[{ fee_head: r.fee_category||'—', fee_head_amount: r.fee_order_amount||0 }]).map((p) => [
        i+1, r.student_name||'—', r.usn||'—', r.fee_category||'—', p.fee_head||'—',
        inr(p.fee_head_amount), inr(r.fee_paid_amount), inr((p.fee_head_amount||0)-(r.fee_paid_amount||0)),
      ])
    ),
  },
  payrecord_dcr: {
    name: 'Pay Record DCR',
    filters: [
      { id:'fee_mode',     label:'Fee Mode',            type:'select', options: FEE_MODES },
      { id:'fee_category', label:'Select fee category', type:'multi',  options: FEE_CATEGORIES },
      { id:'start_date',   label:'Start Date',          type:'date' },
      { id:'to_date',      label:'To Date',             type:'date' },
    ],
    columns:['Report Name','Report Type','Fee Mode','Fee Category','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','fee_mode','fee_category','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Name','Bank','Ref No','Date','Amount (₹)','Method','Status'],
    apiPath: '/api/fee/pay-records',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.name||'—', r.bank_name||'—', r.ref_no||'—',
      fmtD(r.transaction_date), inr(r.transaction_amount), r.method||'—', r.status||'—',
    ]),
  },
  cancellation: {
    name: 'Cancellation Report',
    description: 'Report of cancelled fee orders and refunds.',
    filters: [
      { id:'fee_category', label:'Select fee category', type:'multi', options: FEE_CATEGORIES },
      { id:'start_date',   label:'Start Date',          type:'date' },
      { id:'to_date',      label:'To Date',             type:'date' },
    ],
    columns:['Report Name','Report Type','Fee Category','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','fee_category','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','Refund Amount (₹)','Method','Status','Date'],
    apiPath: '/api/fee/refunds',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', inr(r.refund_amount), r.method||'—', r.refund_status||'—',
      fmtD(r.created_at),
    ]),
  },
  daily_bank: {
    name: 'Daily Bank Report',
    filters: [
      { id:'start_date', label:'Start Date', type:'date' },
      { id:'to_date',    label:'To Date',    type:'date' },
      { id:'fee_mode',   label:'Fee Mode',   type:'select', options: FEE_MODES },
    ],
    columns:['Report Name','Report Type','Fee Mode','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','fee_mode','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Receipt No','Date','Amount (₹)','Method','Bank','Status'],
    apiPath: '/api/fee/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', r.receipt_no||'—',
      fmtD(r.captured_date), inr(r.pay_amount), r.method||'—', r.bank_name||'—', r.pay_status||'—',
    ]),
  },
  daily_collection: {
    name: 'Daily Collection Report',
    filters: [
      { id:'start_date',   label:'Start Date',   type:'date' },
      { id:'to_date',      label:'To Date',       type:'date' },
      { id:'fee_category', label:'Fee Category',  type:'select', options: FEE_CATEGORIES },
    ],
    columns:['Report Name','Report Type','Fee Category','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','fee_category','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Receipt No','Date','Fee Category','Amount (₹)','Method','Status'],
    apiPath: '/api/fee/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', r.receipt_no||'—',
      fmtD(r.captured_date), r.fee_category||'—', inr(r.pay_amount), r.method||'—', r.pay_status||'—',
    ]),
  },
  excess_fee: {
    name: 'Excess Fee Report',
    filters: [
      { id:'programs',     label:'Program Name',  type:'multi', options: PROGRAMS },
      { id:'fee_category', label:'Fee Category',  type:'multi', options: FEE_CATEGORIES },
      { id:'year',         label:'Year',          type:'select',options: YEARS },
    ],
    columns:['Report Name','Report Type','Program','Fee Category','Year','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','program','fee_category','year','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Fee Category','Excess Amount (₹)','Status'],
    apiPath: '/api/fee/orders',
    pdfMapper: (records) => records
      .filter(r => (r.fee_paid_amount||0) > (r.fee_order_amount||0))
      .map((r, i) => [
        i+1, r.student_name||'—', r.usn||'—', r.fee_category||'—',
        inr((r.fee_paid_amount||0)-(r.fee_order_amount||0)), r.order_status||'—',
      ]),
  },
  refund: {
    name: 'Refund Report',
    filters: [
      { id:'start_date',   label:'Start Date',   type:'date' },
      { id:'to_date',      label:'To Date',       type:'date' },
      { id:'fee_category', label:'Fee Category',  type:'select', options: FEE_CATEGORIES },
    ],
    columns:['Report Name','Report Type','Fee Category','Start Date','To Date','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','fee_category','start_date','to_date','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','Refund Amount (₹)','Method','Status','Date'],
    apiPath: '/api/fee/refunds',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', inr(r.refund_amount), r.method||'—', r.refund_status||'—',
      fmtD(r.created_at),
    ]),
  },
  monthly_abstract: {
    name: 'Monthly Abstract Report',
    filters: [
      { id:'month', label:'Month', type:'select', options: MONTHS },
      { id:'year',  label:'Year',  type:'select', options: YEARS_ABS },
    ],
    columns:['Report Name','Report Type','Month','Year','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','month','year','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Receipt No','Date','Amount (₹)','Method','Status'],
    apiPath: '/api/fee/transactions',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', r.receipt_no||'—',
      fmtD(r.captured_date), inr(r.pay_amount), r.method||'—', r.pay_status||'—',
    ]),
  },
  student_consol: {
    name: 'Student-wise Consolidated Balance',
    filters: [
      { id:'programs',     label:'Program Name',  type:'multi', options: PROGRAMS },
      { id:'fee_category', label:'Fee Category',  type:'multi', options: FEE_CATEGORIES },
      { id:'year',         label:'Year',          type:'select',options: YEARS },
      { id:'sort_by',      label:'Sort by',       type:'select',options: SORT_BY_USN },
    ],
    columns:['Report Name','Report Type','Program','Fee Category','Year','Sort By','Requested At','Generated By','Status'],
    rowKeys: ['name','report_type','program','fee_category','year','sort_by','requested_at','generated_by','status'],
    pdfColumns: ['#','Student Name','USN','Program','Total Demand (₹)','Total Collected (₹)','Balance (₹)'],
    apiPath: '/api/fee/orders',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', r.program||'—',
      inr(r.fee_order_amount), inr(r.fee_paid_amount),
      inr((r.fee_order_amount||0)-(r.fee_paid_amount||0)),
    ]),
  },
};

// ── Multi-checkbox dropdown ───────────────────────────────────────────────────
function MultiCheckboxDropdown({ label, options, selected, onChange }) {
  const [open, setOpen] = useState(false);
  const ref = useRef(null);

  useEffect(() => {
    const handler = (e) => { if (ref.current && !ref.current.contains(e.target)) setOpen(false); };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  const toggle = (opt) => {
    if (opt === 'All') { onChange(['All']); return; }
    const next = selected.includes(opt)
      ? selected.filter((s) => s !== opt && s !== 'All')
      : [...selected.filter((s) => s !== 'All'), opt];
    onChange(next.length ? next : ['All']);
  };

  const displayLabel = selected.includes('All') || selected.length === 0
    ? label
    : selected.length === 1 ? selected[0] : `${selected.length} selected`;

  return (
    <div className="relative" ref={ref}>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex items-center justify-between gap-2 min-w-[180px] px-3 py-2 text-sm bg-white border border-slate-300 rounded-lg text-slate-700 hover:border-blue-400 focus:outline-none focus:ring-2 focus:ring-blue-400 transition"
      >
        <span className="truncate">{displayLabel}</span>
        <svg className="w-4 h-4 flex-shrink-0 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
      </button>
      {open && (
        <div className="absolute z-50 mt-1 left-0 bg-white border border-slate-200 rounded-lg shadow-lg min-w-[220px] max-h-72 overflow-y-auto py-1">
          {options.map((opt) => (
            <label key={opt} className="flex items-center gap-2 px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-50 cursor-pointer">
              <input
                type="checkbox"
                checked={selected.includes(opt) || (opt === 'All' && (selected.includes('All') || selected.length === 0))}
                onChange={() => toggle(opt)}
                className="rounded border-slate-300 text-blue-600"
              />
              {opt}
            </label>
          ))}
        </div>
      )}
    </div>
  );
}

function SelectFilter({ label, options, value, onChange }) {
  return (
    <div className="flex flex-col gap-0.5 min-w-[160px]">
      <label className="text-[10px] text-slate-500 uppercase tracking-wide px-0.5">{label}</label>
      <select value={value} onChange={(e) => onChange(e.target.value)}
        className="px-3 py-2 text-sm bg-white border border-slate-300 rounded-lg text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-400">
        {options.map((o) => <option key={o} value={o}>{o}</option>)}
      </select>
    </div>
  );
}

function DateFilter({ label, value, onChange }) {
  return (
    <div className="flex flex-col gap-0.5 min-w-[160px]">
      <label className="text-[10px] text-slate-500 uppercase tracking-wide px-0.5">{label}</label>
      <input type="date" value={value} onChange={(e) => onChange(e.target.value)}
        className="px-3 py-2 text-sm bg-white border border-slate-300 rounded-lg text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-400" />
    </div>
  );
}

function fmtDate(iso) {
  if (!iso) return '—';
  const d = new Date(iso);
  return `${String(d.getDate()).padStart(2,'0')} ${d.toLocaleString('en',{month:'short'})} ${d.getFullYear()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')} ${d.getHours()>=12?'PM':'AM'}`;
}

// ── Report detail page ────────────────────────────────────────────────────────
function ReportDetailPage({ reportKey, onBack }) {
  const cfg = REPORT_CONFIGS[reportKey];

  const initFilters = () => {
    const f = {};
    cfg.filters.forEach((fi) => {
      if (fi.type === 'multi') f[fi.id] = ['All'];
      else if (fi.type === 'date') f[fi.id] = '';
      else f[fi.id] = fi.options[0];
    });
    return f;
  };

  const [filters, setFilters] = useState(initFilters);
  const [rows, setRows] = useState(() => {
    try { return JSON.parse(localStorage.getItem(`fee_report_${reportKey}`) || '[]'); }
    catch { return []; }
  });
  const [generating, setGenerating] = useState(false);
  const [downloadingId, setDownloadingId] = useState(null);
  const [error, setError] = useState(null);

  const saveRows = (r) => {
    setRows(r);
    localStorage.setItem(`fee_report_${reportKey}`, JSON.stringify(r));
  };

  const buildFilterSummary = (f) => {
    const summary = {};
    cfg.filters.forEach((fi) => {
      const v = f[fi.id];
      if (v && v !== '' && !(Array.isArray(v) && v.includes('All'))) {
        summary[fi.label] = Array.isArray(v) ? v.filter(x => x !== 'All').join(', ') : v;
      }
    });
    return summary;
  };

  const fetchAndBuildPdf = async (filterSummary) => {
    const { data: resp } = await api.get(cfg.apiPath, { params: { limit: 500 } });
    const records = resp.data || resp || [];
    const pdfRows = cfg.pdfMapper(records);
    generatePDF({
      title: cfg.name,
      filters: filterSummary,
      columns: cfg.pdfColumns,
      rows: pdfRows,
      filename: `${cfg.name.replace(/\s+/g, '_')}_${Date.now()}`,
    });
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);
    try {
      const filterSummary = buildFilterSummary(filters);
      await fetchAndBuildPdf(filterSummary);

      const today = new Date();
      const newRow = {
        id: Date.now(),
        name: cfg.name,
        report_type: 'PDF',
        program: Array.isArray(filters.programs)
          ? filters.programs.filter(p => p !== 'All').join(', ') || 'All'
          : 'All',
        quota: filters.quota || 'All',
        year: filters.year || 'All',
        term: '1',
        month: filters.month || 'All',
        student_type: filters.student_type || 'All',
        fee_category: Array.isArray(filters.fee_category)
          ? filters.fee_category.filter(f => f !== 'All').join(', ') || 'All'
          : (filters.fee_category || 'All'),
        sort_by: filters.sort_by || 'USN',
        category: filters.category || 'All',
        fee_heads: filters.fee_heads || 'All',
        fee_mode: filters.fee_mode || 'All',
        start_date: filters.start_date || '—',
        to_date: filters.to_date || '—',
        report_type_val: filters.report_type || 'All',
        requested_at: fmtDate(today.toISOString()),
        generated_by: 'Admin',
        status: 'Download',
        _filterSummary: filterSummary,
      };
      saveRows([newRow, ...rows]);
    } catch (err) {
      console.error(err);
      setError('Failed to generate report. Please check your connection and try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = async (row) => {
    setDownloadingId(row.id);
    try {
      await fetchAndBuildPdf(row._filterSummary || {});
    } catch (err) {
      console.error(err);
      setError('Failed to download report. Please try again.');
    } finally {
      setDownloadingId(null);
    }
  };

  const getValue = (row, key) => ({
    name:'',report_type:'',program:'',quota:'',year:'',term:'',month:'',
    student_type:'',fee_category:'',sort_by:'',category:'',fee_heads:'',
    fee_mode:'',start_date:'',to_date:'',report_type_val:'',
    requested_at:'',generated_by:'',status:'', ...row,
  }[key] ?? '—');

  const filterRows = [];
  for (let i = 0; i < cfg.filters.length; i += 4) filterRows.push(cfg.filters.slice(i, i + 4));

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <button onClick={onBack} className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-500 transition-colors">
            <ChevronLeft size={18} />
          </button>
          <div>
            <h1 className="text-lg font-bold text-slate-800">{cfg.name}</h1>
            {cfg.description && <p className="text-xs text-slate-500">{cfg.description}</p>}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => setFilters(initFilters())} className="p-2 rounded-lg hover:bg-slate-100 text-slate-500" title="Reset">
            <RefreshCw size={15} />
          </button>
          <button onClick={handleGenerate} disabled={generating}
            className="flex items-center gap-2 px-4 py-2 text-sm font-semibold bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-60 transition-colors">
            {generating ? 'Generating…' : 'Generate'}
          </button>
        </div>
      </div>

      {error && (
        <div className="px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">{error}</div>
      )}

      <div className="bg-white rounded-xl border border-slate-200 p-4 space-y-3">
        {filterRows.map((row, ri) => (
          <div key={ri} className="flex flex-wrap gap-3">
            {row.map((fi) => {
              if (fi.type === 'multi') {
                return (
                  <div key={fi.id} className="flex flex-col gap-0.5">
                    <label className="text-[10px] text-slate-500 uppercase tracking-wide px-0.5">{fi.label}</label>
                    <MultiCheckboxDropdown
                      label={fi.label}
                      options={fi.options}
                      selected={filters[fi.id] || ['All']}
                      onChange={(v) => setFilters((f) => ({ ...f, [fi.id]: v }))}
                    />
                  </div>
                );
              }
              if (fi.type === 'date') return (
                <DateFilter key={fi.id} label={fi.label} value={filters[fi.id] || ''}
                  onChange={(v) => setFilters((f) => ({ ...f, [fi.id]: v }))} />
              );
              return (
                <SelectFilter key={fi.id} label={fi.label} options={fi.options}
                  value={filters[fi.id] || fi.options[0]}
                  onChange={(v) => setFilters((f) => ({ ...f, [fi.id]: v }))} />
              );
            })}
          </div>
        ))}
      </div>

      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        {rows.length === 0 ? (
          <div className="py-20 text-center">
            <FileText size={36} className="mx-auto mb-3 text-slate-300" />
            <p className="text-sm font-medium text-slate-500">
              To Generate the report, please select all filters above and click on the &apos;Generate&apos; button to download the report.
            </p>
            <p className="text-xs text-slate-400 mt-1">You can select the type of report you want to generate and download it in either Excel or PDF format.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-100">
                  {cfg.columns.map((col) => (
                    <th key={col} className="px-4 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wide whitespace-nowrap">{col}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {rows.map((row) => (
                  <tr key={row.id} className="hover:bg-slate-50 transition-colors">
                    {cfg.rowKeys.map((key, i) => (
                      <td key={i} className="px-4 py-3 text-slate-600 text-xs whitespace-nowrap">
                        {key === 'status' ? (
                          <button
                            onClick={() => handleDownload(row)}
                            disabled={downloadingId === row.id}
                            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-60 transition-colors">
                            <Download size={11} /> {downloadingId === row.id ? 'Downloading…' : 'Download'}
                          </button>
                        ) : key === 'name' ? (
                          <span className="font-medium text-slate-800">{getValue(row, key)}</span>
                        ) : key === 'report_type' ? (
                          <span className="px-2 py-0.5 bg-orange-100 text-orange-700 rounded text-xs font-medium">{getValue(row, key)}</span>
                        ) : getValue(row, key)}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

// ── Main listing page ─────────────────────────────────────────────────────────
export default function FeeReportsPage() {
  const [selected, setSelected] = useState(null);

  if (selected) return <ReportDetailPage reportKey={selected} onBack={() => setSelected(null)} />;

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-blue-600 flex items-center justify-center">
          <BarChart2 size={20} className="text-white" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-slate-800">Fee Reports</h1>
          <p className="text-sm text-slate-500 mt-0.5">Generate and download financial reports</p>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {REPORT_SECTIONS.map((section) => (
          <div key={section.title} className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="px-5 py-4 border-b border-slate-100">
              <h3 className="font-semibold text-slate-800 text-sm">{section.title}</h3>
            </div>
            <div className="p-2">
              {section.reports.map((r) => (
                <button key={r.key} onClick={() => setSelected(r.key)}
                  className="w-full flex items-center justify-between px-4 py-3 text-sm text-slate-700 hover:bg-slate-50 transition-colors rounded-lg group">
                  <span className="group-hover:text-blue-600 transition-colors text-left">{r.name}</span>
                  <ChevronRight size={14} className="text-slate-400 group-hover:text-blue-500 flex-shrink-0" />
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
