import { Home } from 'lucide-react';
import { inr, fmtD } from '../../utils/pdfReport';
import ReportsLayout from '../../components/common/ReportsLayout';

const MONTHS  = ['All','January','February','March','April','May','June','July','August','September','October','November','December'];
const YEARS   = ['All','2024','2025','2026'];
const STATUSES = ['All','Active','Inactive','Graduated'];

// ── Section config ────────────────────────────────────────────────────────────
const REPORT_SECTIONS = [
  {
    title: 'Custom Reports',
    reports: [
      { key: 'day_book',         name: 'Day Book Report' },
      { key: 'daily_collection', name: 'Daily Collection Report' },
      { key: 'monthly_abstract', name: 'Monthly Abstract Report' },
      { key: 'yearly_abstract',  name: 'Yearly Abstract Report' },
    ],
  },
  {
    title: 'Resident Reports',
    reports: [
      { key: 'resident_list',  name: 'Resident List Report' },
      { key: 'occupancy',      name: 'Occupancy Report' },
    ],
  },
  {
    title: 'Financial Reports',
    reports: [
      { key: 'fee_abstract',  name: 'Hostel Fee Abstract Report' },
      { key: 'refund_report', name: 'Refund Report' },
    ],
  },
];

// ── Per-report configs ────────────────────────────────────────────────────────
const REPORT_CONFIGS = {
  day_book: {
    name: 'Day Book Report',
    description: 'Date-wise hostel fee collection register.',
    filters: [
      { id: 'start_date', label: 'Start Date', type: 'date' },
      { id: 'to_date',    label: 'To Date',    type: 'date' },
    ],
    columns:  ['Report Name', 'Report Type', 'Start Date', 'To Date', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'start_date', 'to_date', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Student Name', 'USN', 'Amount (₹)', 'Category', 'Method', 'Date', 'Status'],
    apiPath: '/api/fee/transactions',
    apiParams: { module_name: 'Hostel' },
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', inr(r.pay_amount),
      r.fee_category||'—', r.method||'—', fmtD(r.captured_date||r.created_at), r.pay_status||'—',
    ]),
  },
  daily_collection: {
    name: 'Daily Collection Report',
    description: 'Hostel fee collected for a specific date range.',
    filters: [
      { id: 'start_date',   label: 'Start Date',   type: 'date' },
      { id: 'to_date',      label: 'To Date',       type: 'date' },
      { id: 'fee_category', label: 'Fee Category',  type: 'select', options: ['All', 'Hostel Fee', 'Mess Fee', 'Maintenance', 'Miscellaneous'] },
    ],
    columns:  ['Report Name', 'Report Type', 'Fee Category', 'Start Date', 'To Date', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'fee_category', 'start_date', 'to_date', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Student Name', 'USN', 'Amount (₹)', 'Category', 'Method', 'Date', 'Status'],
    apiPath: '/api/fee/transactions',
    apiParams: { module_name: 'Hostel' },
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', inr(r.pay_amount),
      r.fee_category||'—', r.method||'—', fmtD(r.captured_date||r.created_at), r.pay_status||'—',
    ]),
  },
  monthly_abstract: {
    name: 'Monthly Abstract Report',
    description: 'Month-wise summary of hostel fee collection.',
    filters: [
      { id: 'month', label: 'Month', type: 'select', options: MONTHS },
      { id: 'year',  label: 'Year',  type: 'select', options: YEARS },
    ],
    columns:  ['Report Name', 'Report Type', 'Month', 'Year', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'month', 'year', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Student Name', 'USN', 'Amount (₹)', 'Category', 'Method', 'Date', 'Status'],
    apiPath: '/api/fee/transactions',
    apiParams: { module_name: 'Hostel' },
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', inr(r.pay_amount),
      r.fee_category||'—', r.method||'—', fmtD(r.captured_date||r.created_at), r.pay_status||'—',
    ]),
  },
  yearly_abstract: {
    name: 'Yearly Abstract Report',
    description: 'Annual summary of hostel fee collection.',
    filters: [
      { id: 'year', label: 'Year', type: 'select', options: YEARS },
    ],
    columns:  ['Report Name', 'Report Type', 'Year', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'year', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Student Name', 'USN', 'Amount (₹)', 'Category', 'Method', 'Date', 'Status'],
    apiPath: '/api/fee/transactions',
    apiParams: { module_name: 'Hostel' },
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', inr(r.pay_amount),
      r.fee_category||'—', r.method||'—', fmtD(r.captured_date||r.created_at), r.pay_status||'—',
    ]),
  },
  resident_list: {
    name: 'Resident List Report',
    description: 'Complete list of hostel residents.',
    filters: [
      { id: 'status',       label: 'Status',       type: 'select', options: STATUSES },
      { id: 'hostel_name',  label: 'Hostel',        type: 'select', options: ['All', 'Boys Hostel', 'Girls Hostel', 'PG Hostel'] },
    ],
    columns:  ['Report Name', 'Report Type', 'Status', 'Hostel', 'Requested At', 'Generated By', 'Status Col'],
    rowKeys:  ['name', 'report_type', 'status', 'hostel_name', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Name', 'USN', 'Room No', 'Hostel', 'Mobile', 'Program', 'Status'],
    apiPath: '/api/hostel/students',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.name||r.student_name||'—', r.usn||'—', r.room_number||'—',
      r.hostel_name||'—', r.mobile_number||'—', r.program||'—', r.status||'—',
    ]),
  },
  occupancy: {
    name: 'Occupancy Report',
    description: 'Hostel-wise occupancy and room utilisation.',
    filters: [
      { id: 'hostel_name', label: 'Hostel', type: 'select', options: ['All', 'Boys Hostel', 'Girls Hostel', 'PG Hostel'] },
    ],
    columns:  ['Report Name', 'Report Type', 'Hostel', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'hostel_name', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Name', 'USN', 'Room No', 'Hostel', 'Admission Date', 'Status'],
    apiPath: '/api/hostel/students',
    pdfMapper: (records) => records
      .filter(r => r.status === 'Active')
      .map((r, i) => [
        i+1, r.name||r.student_name||'—', r.usn||'—', r.room_number||'—',
        r.hostel_name||'—', fmtD(r.admission_date||r.created_at), r.status||'—',
      ]),
  },
  fee_abstract: {
    name: 'Hostel Fee Abstract Report',
    description: 'Abstract of all hostel fee collections.',
    filters: [
      { id: 'year',  label: 'Year',  type: 'select', options: YEARS },
      { id: 'month', label: 'Month', type: 'select', options: MONTHS },
    ],
    columns:  ['Report Name', 'Report Type', 'Year', 'Month', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'year', 'month', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Student Name', 'USN', 'Amount (₹)', 'Category', 'Method', 'Date', 'Status'],
    apiPath: '/api/fee/transactions',
    apiParams: { module_name: 'Hostel' },
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.student_name||'—', r.usn||'—', inr(r.pay_amount),
      r.fee_category||'—', r.method||'—', fmtD(r.captured_date||r.created_at), r.pay_status||'—',
    ]),
  },
  refund_report: {
    name: 'Refund Report',
    description: 'Hostel fee refunds processed.',
    filters: [
      { id: 'start_date', label: 'Start Date', type: 'date' },
      { id: 'to_date',    label: 'To Date',    type: 'date' },
    ],
    columns:  ['Report Name', 'Report Type', 'Start Date', 'To Date', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'start_date', 'to_date', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Student Name', 'USN', 'Amount (₹)', 'Refund Status', 'Date'],
    apiPath: '/api/fee/refunds',
    pdfMapper: (records) => records
      .filter(r => r.module_name === 'Hostel' || !r.module_name)
      .map((r, i) => [
        i+1, r.student_name||'—', r.usn||'—', inr(r.refund_amount),
        r.refund_status||'—', fmtD(r.created_at),
      ]),
  },
};

export default function HostelReportsPage() {
  return (
    <ReportsLayout
      title="Hostel Reports"
      subtitle="Generate and download hostel reports"
      icon={Home}
      iconBg="bg-cyan-600"
      sections={REPORT_SECTIONS}
      configs={REPORT_CONFIGS}
      storagePrefix="hostel_report"
    />
  );
}
