import { UserSquare2 } from 'lucide-react';
import { inr } from '../../utils/pdfReport';
import ReportsLayout from '../../components/common/ReportsLayout';

const PROGRAMS = ['All','Computer Science and Engineering','Electronics and Communication Engineering','Mechanical Engineering','Civil Engineering','Electrical and Electronics Engineering'];
const YEARS    = ['All','2019','2020','2021','2022','2023','2024','2025'];
const STATUSES = ['All','Active','Inactive'];
const INDUSTRIES = ['All','Information Technology','Manufacturing','Finance','Healthcare','Education','Government','Other'];

// ── Section config ────────────────────────────────────────────────────────────
const REPORT_SECTIONS = [
  {
    title: 'Custom Reports',
    reports: [
      { key: 'alumni_directory',   name: 'Alumni Directory Report' },
      { key: 'placement_report',   name: 'Placement Report' },
      { key: 'higher_education',   name: 'Higher Education Report' },
    ],
  },
  {
    title: 'Academic Reports',
    reports: [
      { key: 'program_wise',  name: 'Program-wise Breakdown Report' },
      { key: 'year_wise',     name: 'Year-wise Graduation Report' },
      { key: 'batch_summary', name: 'Batch Summary Report' },
    ],
  },
  {
    title: 'Career Reports',
    reports: [
      { key: 'industry_report', name: 'Industry Breakdown Report' },
      { key: 'company_report',  name: 'Company-wise Placement Report' },
    ],
  },
];

// ── Per-report configs ────────────────────────────────────────────────────────
const REPORT_CONFIGS = {
  alumni_directory: {
    name: 'Alumni Directory Report',
    description: 'Complete list of all alumni with contact and career details.',
    filters: [
      { id: 'status',  label: 'Status',  type: 'select', options: STATUSES },
      { id: 'program', label: 'Program', type: 'select', options: PROGRAMS },
      { id: 'year',    label: 'Grad Year', type: 'select', options: YEARS },
    ],
    columns:  ['Report Name', 'Report Type', 'Status', 'Program', 'Grad Year', 'Requested At', 'Generated By', 'Status Col'],
    rowKeys:  ['name', 'report_type', 'status', 'program', 'year', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Name', 'USN', 'Program', 'Batch', 'Grad Year', 'Email', 'Mobile', 'Status'],
    apiPath: '/api/alumni',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.name||'—', r.usn||'—', r.program||'—', r.batch||'—',
      r.graduation_year||'—', r.personal_email||r.email||'—',
      r.mobile_number||'—', r.status||'—',
    ]),
  },
  placement_report: {
    name: 'Placement Report',
    description: 'Alumni who are currently employed with company and designation details.',
    filters: [
      { id: 'program',  label: 'Program',  type: 'select', options: PROGRAMS },
      { id: 'year',     label: 'Grad Year', type: 'select', options: YEARS },
      { id: 'industry', label: 'Industry', type: 'select', options: INDUSTRIES },
    ],
    columns:  ['Report Name', 'Report Type', 'Program', 'Grad Year', 'Industry', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'program', 'year', 'industry', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Name', 'USN', 'Program', 'Grad Year', 'Company', 'Designation', 'Industry', 'Location'],
    apiPath: '/api/alumni',
    pdfMapper: (records) => records
      .filter(r => r.current_company)
      .map((r, i) => [
        i+1, r.name||'—', r.usn||'—', r.program||'—', r.graduation_year||'—',
        r.current_company||'—', r.current_designation||'—', r.industry||'—', r.current_location||'—',
      ]),
  },
  higher_education: {
    name: 'Higher Education Report',
    description: 'Alumni who pursued higher education after graduation.',
    filters: [
      { id: 'program', label: 'Program',  type: 'select', options: PROGRAMS },
      { id: 'year',    label: 'Grad Year', type: 'select', options: YEARS },
    ],
    columns:  ['Report Name', 'Report Type', 'Program', 'Grad Year', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'program', 'year', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Name', 'USN', 'Program', 'Grad Year', 'Higher Ed Institute', 'Course', 'CGPA'],
    apiPath: '/api/alumni',
    pdfMapper: (records) => records
      .filter(r => r.higher_education)
      .map((r, i) => [
        i+1, r.name||'—', r.usn||'—', r.program||'—', r.graduation_year||'—',
        r.higher_education_institute||'—', r.higher_education_course||'—', r.cgpa||'—',
      ]),
  },
  program_wise: {
    name: 'Program-wise Breakdown Report',
    description: 'Count of alumni grouped by engineering program.',
    filters: [
      { id: 'year', label: 'Grad Year', type: 'select', options: YEARS },
    ],
    columns:  ['Report Name', 'Report Type', 'Grad Year', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'year', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Name', 'USN', 'Program', 'Batch', 'Grad Year', 'CGPA', 'Status'],
    apiPath: '/api/alumni',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.name||'—', r.usn||'—', r.program||'—',
      r.batch||'—', r.graduation_year||'—', r.cgpa||'—', r.status||'—',
    ]),
  },
  year_wise: {
    name: 'Year-wise Graduation Report',
    description: 'Alumni grouped by their graduation year.',
    filters: [
      { id: 'year', label: 'Grad Year', type: 'select', options: YEARS },
    ],
    columns:  ['Report Name', 'Report Type', 'Grad Year', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'year', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Name', 'USN', 'Program', 'Batch', 'Grad Year', 'CGPA'],
    apiPath: '/api/alumni',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.name||'—', r.usn||'—', r.program||'—',
      r.batch||'—', r.graduation_year||'—', r.cgpa||'—',
    ]),
  },
  batch_summary: {
    name: 'Batch Summary Report',
    description: 'Summary of alumni per batch with placement statistics.',
    filters: [
      { id: 'program', label: 'Program', type: 'select', options: PROGRAMS },
    ],
    columns:  ['Report Name', 'Report Type', 'Program', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'program', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Name', 'USN', 'Batch', 'Program', 'Grad Year', 'Company', 'Status'],
    apiPath: '/api/alumni',
    pdfMapper: (records) => records.map((r, i) => [
      i+1, r.name||'—', r.usn||'—', r.batch||'—',
      r.program||'—', r.graduation_year||'—', r.current_company||'Not Placed', r.status||'—',
    ]),
  },
  industry_report: {
    name: 'Industry Breakdown Report',
    description: 'Distribution of employed alumni across industries.',
    filters: [
      { id: 'industry', label: 'Industry', type: 'select', options: INDUSTRIES },
      { id: 'year',     label: 'Grad Year', type: 'select', options: YEARS },
    ],
    columns:  ['Report Name', 'Report Type', 'Industry', 'Grad Year', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'industry', 'year', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Name', 'Program', 'Grad Year', 'Company', 'Designation', 'Industry', 'Location'],
    apiPath: '/api/alumni',
    pdfMapper: (records) => records
      .filter(r => r.industry || r.current_company)
      .map((r, i) => [
        i+1, r.name||'—', r.program||'—', r.graduation_year||'—',
        r.current_company||'—', r.current_designation||'—', r.industry||'—', r.current_location||'—',
      ]),
  },
  company_report: {
    name: 'Company-wise Placement Report',
    description: 'Alumni placed in each company.',
    filters: [
      { id: 'year', label: 'Grad Year', type: 'select', options: YEARS },
    ],
    columns:  ['Report Name', 'Report Type', 'Grad Year', 'Requested At', 'Generated By', 'Status'],
    rowKeys:  ['name', 'report_type', 'year', 'requested_at', 'generated_by', 'status'],
    pdfColumns: ['#', 'Name', 'USN', 'Program', 'Grad Year', 'Company', 'Designation', 'Industry'],
    apiPath: '/api/alumni',
    pdfMapper: (records) => records
      .filter(r => r.current_company)
      .sort((a, b) => (a.current_company||'').localeCompare(b.current_company||''))
      .map((r, i) => [
        i+1, r.name||'—', r.usn||'—', r.program||'—',
        r.graduation_year||'—', r.current_company||'—', r.current_designation||'—', r.industry||'—',
      ]),
  },
};

export default function AlumniReportsPage() {
  return (
    <ReportsLayout
      title="Alumni Reports"
      subtitle="Generate and download alumni reports"
      icon={UserSquare2}
      iconBg="bg-purple-600"
      sections={REPORT_SECTIONS}
      configs={REPORT_CONFIGS}
      storagePrefix="alumni_report"
    />
  );
}
