import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const INSTITUTION = 'Jnana Ganga Institute of Technology';

/**
 * Generate a professional PDF report and trigger browser download.
 *
 * @param {object} opts
 * @param {string}   opts.title       - Report title shown in header
 * @param {object}   opts.filters     - Active filter key/value map (for summary line)
 * @param {string[]} opts.columns     - Table column headers
 * @param {Array[]}  opts.rows        - 2D array of row cell values
 * @param {string}   [opts.filename]  - Override download filename
 * @param {'portrait'|'landscape'} [opts.orientation='landscape']
 */
export function generatePDF({ title, filters = {}, columns, rows, filename, orientation = 'landscape' }) {
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 14;

  // ── Header band ─────────────────────────────────────────────────────────────
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, W, 28, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text(INSTITUTION, W / 2, 11, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(title, W / 2, 20, { align: 'center' });

  const now = new Date();
  const stamp = now.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
    + '  ' + now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
  doc.setFontSize(7.5);
  doc.text(stamp, W - M, 24, { align: 'right' });

  let y = 34;

  // ── Filter summary ──────────────────────────────────────────────────────────
  const activeFilters = Object.entries(filters).filter(([, v]) => {
    if (!v || v === '') return false;
    if (Array.isArray(v)) return v.length > 0 && !(v.length === 1 && v[0] === 'All');
    return v !== 'All' && v !== 'Select' && v !== 'Select Report Type';
  });

  if (activeFilters.length > 0) {
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.setFont('helvetica', 'bold');
    doc.text('Filters: ', M, y);
    doc.setFont('helvetica', 'normal');
    const txt = activeFilters
      .map(([k, v]) => {
        const label = k.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
        const val = Array.isArray(v) ? v.filter(x => x !== 'All').join(', ') || 'All' : v;
        return `${label}: ${val}`;
      })
      .join('  ·  ');
    const wrapped = doc.splitTextToSize(txt, W - M - 28);
    doc.text(wrapped, M + 18, y);
    y += wrapped.length * 4.5 + 3;
  }

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Records: ${rows.length}`, M, y);
  y += 5;

  // ── Data table ──────────────────────────────────────────────────────────────
  autoTable(doc, {
    startY: y,
    head: [columns],
    body: rows.length > 0 ? rows : [Array(columns.length).fill('No data available')],
    margin: { left: M, right: M },
    tableWidth: 'auto',
    styles: {
      fontSize: 7.5,
      cellPadding: 2.5,
      textColor: [51, 65, 85],
      lineColor: [226, 232, 240],
      lineWidth: 0.2,
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didDrawPage: (data) => {
      doc.setFontSize(7.5);
      doc.setTextColor(148, 163, 184);
      doc.text(`Page ${data.pageNumber}`, W / 2, H - 7, { align: 'center' });
      doc.text(INSTITUTION, M, H - 7);
      doc.text('Generated by: Admin', W - M, H - 7, { align: 'right' });
    },
  });

  const safeName = (filename || `${title.replace(/\s+/g, '_')}_${Date.now()}`).replace(/[^a-zA-Z0-9_-]/g, '_');
  doc.save(`${safeName}.pdf`);
}

// ── Helpers ──────────────────────────────────────────────────────────────────
export function inr(n) {
  if (n == null || n === '') return '—';
  return Number(n).toLocaleString('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
}

export function fmtD(dateStr) {
  if (!dateStr) return '—';
  return new Date(dateStr).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}
